name = "tracknstick-api"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB" # Will be available in your Worker as env.DB
database_name = "tracknstick-db"
database_id = "d828b4a9-4ae4-4af3-af29-be4c27ae42fc"

[site]
bucket = "./public" 